version: '3.1'

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
  
  aspnet:
    container_name: 'goalmanagementapi'
    image: 'goalmanagementapi'
    build:
      context: ./SothemaGoalManagement.API
      dockerfile: .docker/aspnetcore.production.dockerfile
    ports:
     - "5000:5000"
    environment:
      DB_CONNECTION_STRING:  "Server=domain\\server;Database=gmDB;User Id=gm; Password=P@ssw0rd;"
    networks:
      - app-network
  
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
